services:
  - type: web
    name: mercadopago-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: ACCESS_TOKEN
        sync: false
